### ISSUE TITLE
Crashes on Windows when volume of working directory and of registry/data_dir differ 

### ISSUE THREAD

**Issue by PolMine** [PolMine/RcppCWB#1]
In the registry file of a corpus, the path to the data directory needs to be stated without the drive letter (i.e. C:/PATH/TO/CORPUS/DATA will not work, but /PATH/TO/CORPUS/DATA will be ok). As far as I understand it, the corpus library (CL), and the Corpus Query Processor (CQP) will assume that the corpus data will be on the drive of the current working directory.

So when working with RcppCWB, you need to make sure that the drive volume of your current working directory and the drive volume of your registry directory / corpus data directories are identical. The simple solution to achieve this is to use the setwd() function.

We encountered the issue in a mindbreaking manner when having the git repository for RcppCWB on drive C: on a Windows test environment, and the installation of all R packages on drive D: - R CMD check will fail in this scenario.

At present, when drive letters are different, you may see a warning in interactive mode, but R will crash. Certainly, we need do replace warning() with stop().

One odd thing: In v0.1.7, things worked. Maybe we had an approach then (passing drive letter as part of path to registry directory?) that we are not following up in the newer versions of RcppCWB. Need to follow up on this.

**Comment by ablaette** [comment]
This has been solved: The drive letter can be included in the path when the path is wrapped in quotation marks.

**Comment by PolMine** [comment]
The error can be omitted if a path including a drive letter is wrapped in quotation marks. Solved.
