### ISSUE TITLE
Clean up tools directory (setpaths.R)

### ISSUE THREAD

**Issue by PolMine** [PolMine/RcppCWB#10]
The new RcppCWB version 0.2.8 will rely on a temporary registry directory as the location for a registry file with correct paths to the corpora within a package. This is necessary to cope with the planned 'staged installs' of the CRAN build machinery.

I wanted to see whether the new RcppCWB version passes all CRAN checks. If yes, some cleaning up is possible with the configure script (delete Step 3 commented out at this time), and the file setpaths.R in the tools directory can be removed.

**Comment by ablaette** [comment]
Indeed this file is unused and I have deleted it. Just as a mental note: The nice thing about setting paths upon installation was that you would not need the temporary registry directory. However, there is no way how you could set the paths with the distribution of binaries (for Windows and macOS). So even thought there may be hickups when you load RcppCWB and polmineR, the temporary registry is the way to go.
