### ISSUE TITLE
Corpora are not found when RcppCWB is loaded after polmineR

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/RcppCWB#13]
Loading `RcppCWB` after `polmineR` seems to confuse the latter. A registry reset somehow?
In any case, I cannot load any corpora when I want to load RcppCWB explicitly in this order:

```
library(polmineR)
library(RcppCWB)
use("polmineR")
```

> ... activating corpus: GERMAPARLMINI (version: 0.0.1 | build date: 2019-02-23)
Error in file(con, "r") : cannot open the connection
In addition: Warning message:
In file(con, "r") :

The other way around works fine.

```
library(RcppCWB)
library(polmineR)
use("polmineR")
```

I could understand when a registry reset has to take place here. Maybe it would be nice then to check if polmineR is already loaded and to issue a meaningful warning. The problem here remains that once the error occurs the registry won't work even if we reload polmineR afterwards (library(polmineR)). 

Session Info:

> [1] RcppCWB_0.2.8       polmineR_0.8.0.9023

**Comment by ablaette** [comment]
RcppCWB still uses a temporary registry, this is a requirement to have test data available. But it does not reset the CORPUS_REGISTRY environment variable. Independent from the sequence, RcppCWB and polmineR can now be loaded without warnings, namespace collissions etc.
