### ISSUE TITLE
Potential issue when installing RcppCWB on Raspberry Pi

### ISSUE THREAD

**Issue by PolMine** [PolMine/RcppCWB#15]
I can install RcppCWB on a Raspberry Pi, but RcppCWB shows the following issue during the installation process. 

* installing *source* package ‘RcppCWB’ ...
** package ‘RcppCWB’ successfully unpacked and MD5 sums checked
* operating system detected for CWB configuration: Linux
* Linux distribution ID: raspbian (unsupported, adapting the configuration may be necessary)
./configure: 1: ./configure: armv7l: not found
* unknown architecture (), using Linux config as default
* using CWB platform configuration file: linux

So it works, but not in an anticipated manner.

**Comment by ablaette** [comment]
A minor modification of the configure script I have introduced recently to avoid a similar error message when testing RcppCWB in Fedora Docker container on an Apple M1 architecture removes this issue. You still see the information that the architecture (armv7l) is unknown, but the linux default configuration file works.
