### ISSUE TITLE
Rcpp implementation of s_attribute_decode crashes on Windows

### ISSUE THREAD

**Issue by PolMine** [PolMine/RcppCWB#2]
But the R implementation works. The current solution is that the Rcpp implementation of s_attribute_decode is not tested and is not dealt with in an example. Not nice, obviously.

**Comment by ablaette** [comment]
Returning to this issue after a while ... The Implmentation was simply incomplete. I added the missing code and added a check of the R against the Rcpp method. Everything seems to work nicely, Windows included. So I close the issue.
