### ISSUE TITLE
Installation might fail if cwb libraries already exist 

### ISSUE THREAD

**Issue by ChristophLeonhardt** [PolMine/RcppCWB#6]
On my system, a preexisting libcl library in /usr/local/lib/ prevented the newly compiled RcppCWB libraries from being used, resulting in failed installations.

Solved by renaming preexisting libcl, but maybe renaming RcppCWB libraries would be more adequate.

**Comment by ablaette** [comment]
This is a special scenario, but not a unrealistic one. The configure script should check whether libcl is present at the default location. Maybe it is possible to purposefully exclude a library. At least, there should be a meaningful warning message that the "original" libcl and the one compiled when building the (temporary) libcl of RcppCWB may conflict.

**Comment by ablaette** [comment]
Returning to and re-thinking this issue, I think this is an extremely unlikely scenario. 

What could have happened: If you did not use Homebrew to get pcre and compiled it yourself, the static pcre library(file libpcre.a) would be in /usr/local/lib and `pcre-config --libs`, which is used during the CWB installation process would return this directory. Old versions of CWB have moved the libcl.a file to this directory, too.

Then, during RcppCWB installation, `pcre-config --libs` is used and if the flag -lpcre has been there before -libcl, it would find the original CWB libcl static lib before finding the libcl that is compiled by RcppCWB as an intermediate product. 

Recent versions of CWB create a cwb-specific subdirectory in /usr/local/lib and most Users use Homebrew. So it is not likely that RcppCWB accidentily finds the original CWB libcl.a file when linking.

Please re-open the issue if necessary! I cannot reproduce the issue.
