### ISSUE TITLE
No call to 'ranlib' for static libraries libcl, libcqp and libcwb 

### ISSUE THREAD

**Issue by PolMine** [PolMine/RcppCWB#9]
The upcoming RcppCWB version 0.2.8 tries to solve the Solaris portability issue. Part of the solution is to skip a call to 'ranlib' in the Makefiles for the 'libcl', the 'libcwb' and the 'libcqp' static libraries that are compiled as an intermediate step on the way towards the dynamic library that is part of the package. First I tried to replace the call to 'ranlib' by a call 'ar -s'. But this is not accepted on Solaris either.

Everythink seems to work without creating the index, but maybe there is a way to minimize the intervention in the original CWB Makefile.

**Comment by ablaette** [comment]
Issues with portability to Solaris have caused me extensive headaches last year, but everything seems to work nicely up to know. So I close the issue.
